[tools]
cargo-binstall = "latest"
"cargo:ripgrep" = "latest"
dotnet = "latest"
fd = "latest"
fzf = "latest"
ghcup = "latest"
go = "latest"
java = "latest"
node = "22.15.1"
pipx = "latest"
poetry = "latest"
rust = "latest"
zig = "latest"
neovim = "latest"
python = "3.12.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
